### ISSUE TITLE
version 5 todos

### ISSUE THREAD

**Issue by axten** [nikita-kit/generator-nikita#135]
- [x] add react and make jsb optional #134 
- [x] overhaul the generator itself #139
- [x] add favicon generator #132
- [x] add eslintrc and stylelint rc for IDEs
- [x] update eslint-config
- [x] update dependencies
- [x] remove assemble #138 
- [x] remove grunt accessibilty #133 
- [x] remove form framework #140
- [x] replace select2 by choices
- [x] replace swiper by siema slider
- [x] remove jquery
