### ISSUE TITLE
version 4 todos

### ISSUE THREAD

**Issue by axten** [nikita-kit/generator-nikita#91]
- [x] remove bower #94 
- [x] remove compass & ruby sass #95
- [x] remove default template and unused default-only packages #104
  - [x] remove photobox
  - [x] remove svgsprite
  - [x] remove pagespeed
  - [x] remove phantomas
  - [x] remove jsdoc
  - [x] remove group-css-media-queries
  - [x] remove cssSplit
- [x] update webpack #92 #96
- [x] update eslint #93
- [x] update stylelint, setup autofixing and pre commit hook #97
- [x] add [webpack-bundle-analyzer](https://github.com/th0r/webpack-bundle-analyzer) #100
- [x] add [jest](https://facebook.github.io/jest/) #103
- [x] [split](http://ericnish.io/blog/how-to-neatly-separate-grunt-files/) grunt config #101
- [x] update browserlist #102
- [x] check compatibility with node <=8 #98 
- [x] reworked imagemin #116 
- [x] tune readme (and many more) #117
- [x] remove grunt-styleguide #118
- [x] replace cssmin with csso #119
- [x] add symfony template (web/static/) #120
- [x] fix restore behavior of generator not working properly #120
- [x] improve generator readme (explain generator main questions) #121
- [x] add wordpress template (static/) #123
- [x] add downgrade prevention when rerun generator #124
- [x] add component structure #125
- [x] make pre-commit hook optional #126
- [ ] generate all template varieties with travis

**Comment by axten** [comment]
@DracoBlue, can you review the default-only packages i wont to remove (see above)?

**Comment by DracoBlue** [comment]
LGTM
